apiVersion: v1
kind: ConfigMap
metadata:
  name: dapdap-job-conf
  namespace: dapdap-pre
data:
  config.toml: |
    debug=false
    timeout=60
    questInterval=10
    RankInterval=900
    GalxeInterval=30
    LaunchpadPoolInterval=300
    CompassQuestTradeRank=[]
    CompassQuestParticle=0
    CompassQuestMetaStreet=0
    CompassSummary=[]
    CompassSummaryChain=[]
    CompassLeaderBoard=[]
    CompassLeaderBoardChain=[]
    InitActionDapp=false
    CompassProjectQuestEnable=false
    CompassProjectId=0
    DappTrade=0
    DappTradeTime=[]
    DappTradeBridgeType=""
    SpinCompass=[]
    SpinCompassReward=[]
    LaunchpadRewardPool=""
    GemLogo = "https://assets.dapdap.net/images/gem.png"
    ActivityInviteGem = 10
    NanLongDaoAccountId = 35736
    NanLongDaoLogo = "https://assets.dapdap.net/images/namlongdao_claim.png"
    KolLogo = "https://assets.dapdap.net/images/kol.png"
    EnableMedalFunction = false
    UpdatePriceFromDB3=["LORE","loreUSD"]
    CampaignSummary=[5]
    CampaignLeaderboard=[5]
    CampaignLeaderboardToken=[5]
    CampaignMedal=[]
    
    [CampaignLeaderboardBonus]
    "5" = 1.5
  
    [CampaignLeaderboardExtraBonus]
    "5" = 500
          
    [log]
    dir = ""
    
    [DB3]
    AccessKey="${{ DB3_ACCESS_KEY }}"
    ApiHost="https://api.db3.app"
    
    
    [pgsql]
    [pgsql.db]
    dsn = "host=${{ DATABASE_HOST }} port=5432 user=dapdap_pre password=${{ DATABASE_PASSWORD }} dbname=dapdap_pre sslmode=disable"
    active = 50
    idle = 50
    
    
    [redis]
    proto = "tcp"
    addr = "${{ REDIS_HOST }}:${{ REDIS_PORT }}"
    idle = 10
    active = 10
    idleTimeout = 10
    db = ${{ REDIS_DB }}
    password = "${{ REDIS_PASSWORD }}"
    useTls = true
    
    [galxe]
    enable=false
    token=""
    credId=""
    
    [Chains]
    "1"="https://eth.llamarpc.com"
    "8453"="https://mainnet.base.org"
    "56"="https://bsc-dataseed.bnbchain.org"
    "59144"="https://rpc.linea.build"
    "81457"="https://rpc.blast.io"
    "1101"="https://zkevm-rpc.com"
    "324"="https://mainnet.era.zksync.io"
    "534352"="https://rpc.scroll.io"
    "3776"="https://rpc.startale.com/astar-zkevm"
    "196"="https://xlayerrpc.okx.com"
    "137"="https://polygon-rpc.com"
    "42161"="https://arb1.arbitrum.io/rpc"
    "34443"="https://mainnet.mode.network"
  
    [MultiCallContract]
    "1"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "42161"="0x99D73e5d83148FA2b41248059061f91703Cf0516"
    "43114"="0x072aD7f291AED59E7C4974EbdcF73B79DAC89051"
    "8453"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "56"="0xfF6FD90A470Aaa0c1B8A54681746b07AcdFedc9B"
    "100"="0xAbd2FE441318a73414e3fa93297D3Bdb036CB2Fa"
    "59144"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "5000"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "10"="0xD9bfE9979e9CA4b2fe84bA5d4Cf963bBcB376974"
    "137"="0xed386Fe855C1EFf2f843B910923Dd8846E45C5A4"
    "324"="0x1ADC6Ac76c6d35cED013cA0513919f7f53586fAf"
    "169"="0xE4f7776c753aF46D2aa23e3348d17548C86DC47D"
    "1088"="0xc39aBB6c4451089dE48Cffb013c39d3110530e5C"
    "534352"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "1101"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "81457"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "3776"="0xcA11bde05977b3631167028862bE2a173976CA11"
    "196"="0x2D04a0885df6cdcAE24453eCCd07122a52534763"
    "34443"="0xcA11bde05977b3631167028862bE2a173976CA11"
    
    [CoinGecko]
    PriceApi="https://pro-api.coingecko.com/api/v3/simple/price"
    MarketApi="https://pro-api.coingecko.com/api/v3/coins/markets"
    MarketChartApi="https://pro-api.coingecko.com/api/v3/coins/%s/market_chart"
    ApiKey="${{ COIN_GECKO_API_KEY }}"
    UpdatePriceInterval=1800
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dapdap-job
    namespace: dapdap-pre
spec:
    replicas: 1
    selector:
        matchLabels:
            app: dapdap-job
    template:
        metadata:
            labels:
                app: dapdap-job
        spec:
            initContainers:
                - name: init-k8s-secret-fetcher
                  image: bob-ap-southeast-1.cr.bytepluses.com/v1/init-k8s-secret-fetcher:latest
                  envFrom:
                      - secretRef:
                            name: dapdap-secret
                  volumeMounts:
                      - name: "config"
                        mountPath: "/config"
                      - name: "rw-config"
                        mountPath: "/rw-config"
            containers:
                - name: dapdap-job
                  args:
                      - "-conf=/config/config.toml"
                  image: bob-ap-southeast-1.cr.bytepluses.com/v1/dapdap-job:latest
                  resources:
                      limits:
                          memory: "1000M"
                          cpu: "0.3"
                      requests:
                          memory: "100M"
                          cpu: "0.1"
                  volumeMounts:
                      - name: "rw-config"
                        mountPath: "/config"
            volumes:
                - name: config
                  configMap:
                      name: dapdap-job-conf
                      items:
                          - key: config.toml
                            path: config.toml
                - name: rw-config
                  emptyDir: {}