apiVersion: v1
kind: ConfigMap
metadata:
  name: beratown-api-conf
  namespace: beratown-pre
data:
  REDIS_USE_TLS: "1"
  CHAIN_ID: "80094"
  CHAINS_ID: "[1,42161,80094]"
  CHAINS_RPC: "[\"https://1.rpc.thirdweb.com/bdb8d1ba2cad4342c916d177b6927163\", \"https://42161.rpc.thirdweb.com/bdb8d1ba2cad4342c916d177b6927163\", \"https://rpc.berachain.com\"]"
  DATABASE_POOL_MAXSIZE: "5"
  API_LIMIT_STORAGE_REDIS: "0"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beratown-api
  namespace: beratown-pre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beratown-api
  template:
    metadata:
      labels:
        app: beratown-api
    spec:
      containers:
        - name: beratown-api
          image: bob-ap-southeast-1.cr.bytepluses.com/v1/beratown-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              uvicorn main:app --host 0.0.0.0 --port 8101 --no-access-log --workers 1 2>&1 | tee /dev/fd/2 > ./app.log
          envFrom:
            - configMapRef:
                name: beratown-api-conf
            - secretRef:
                name: beratown-secret
          resources:
            limits:
              memory: "1000M"
              cpu: "0.3"
            requests:
              memory: "100M"
              cpu: "0.1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8101
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8101
            timeoutSeconds: 30
          ports:
            - containerPort: 8101

---
apiVersion: v1
kind: Service
metadata:
  name: beratown-api-svc
  namespace: beratown-pre
spec:
  type: ClusterIP
  selector:
    app: beratown-api
  ports:
    - port: 8101
      protocol: TCP
      name: port8101