apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ops-storages
provisioner: ebs.csi.volcengine.com
parameters:
  ChargeType: PostPaid
  type: ESSD_PL0
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate