# nonk8s
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-scraper
  namespace: prometheus
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: metrics
      path: /metrics

