alertmanager:
  ingress:
    enable: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - alertmanager.bobdev.link
    tls:
     - secretName: bobdev-link-tls
       hosts:
       - alertmanager.bobdev.link
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ops-storages
        resources:
          requests:
            storage: 50Gi
grafana:
  ingress:
    enable: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - grafana.bobdev.link
    tls:
     - secretName: bobdev-link-tls
       hosts:
       - grafana.bobdev.link
prometheus:
  ingress:
    enable: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - prometheus.bobdev.link
    tls:
     - secretName: bobdev-link-tls
       hosts:
       - prometheus.bobdev.link
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: ops-storages
        resources:
          requests:
            storage: 50Gi