apiVersion: v1
kind: ConfigMap
metadata:
  name: dapdap-uniswap-smart-router-conf
  namespace: dapdap-pre
data:
  JSON_RPC_PROVIDER: 'https://ethereum.blockpi.network/v1/rpc/c43cf5556a42c2e8689613010b287dbed77b8d4e'
  JSON_RPC_PROVIDER_OPTIMISM: 'https://optimism.blockpi.network/v1/rpc/65df1b8055a8721d2c4fa12326731065cd713ab1'
  JSON_RPC_PROVIDER_ARBITRUM_ONE: 'https://arbitrum.blockpi.network/v1/rpc/3d394eeb24fbafa0a02feebdb0ae1e57efac0b92'
  JSON_RPC_PROVIDER_POLYGON: 'https://polygon.blockpi.network/v1/rpc/ea85a35602e377c6c7531ca4572dfacf5dece0c8'
  JSON_RPC_PROVIDER_CELO: 'https://rpc.ankr.com/celo/fa8cecf2398fe6a2d19fea8b78b641c35edb7bdf60e5bf7a3883565532ba07ef'
  JSON_RPC_PROVIDER_BNB: 'https://bsc.blockpi.network/v1/rpc/de0f17bc8d626ecdfabea1ef6bb029d5a2746c21'
  JSON_RPC_PROVIDER_AVALANCHE: 'https://avalanche.blockpi.network/v1/rpc/0d6b707292fe05e1c18bbfee82bc73246f032315'
  JSON_RPC_PROVIDER_BASE: 'https://base.blockpi.network/v1/rpc/cfda722ee7fc992bae25aae68db68718f24e4823'
  JSON_RPC_PROVIDER_LINEA_GORLI: 'https://rpc.goerli.linea.build'
  JSON_RPC_PROVIDER_LINEA: 'https://rpc.linea.build'
  JSON_RPC_PROVIDER_SCROLL: 'https://scroll.blockpi.network/v1/rpc/public'
  JSON_RPC_PROVIDER_BASE_SEPOLIA: 'https://sepolia.base.org'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapdap-uniswap-smart-router
  namespace: dapdap-pre
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dapdap-uniswap-smart-router
  template:
    metadata:
      labels:
        app: dapdap-uniswap-smart-router
    spec:
      containers:
        - name: dapdap-uniswap-smart-router
          image: bob-ap-southeast-1.cr.bytepluses.com/v1/dapdap-uniswap-smart-router:latest
          command: ["node", "build/main/index.js"]
          envFrom:
            - configMapRef:
                name: dapdap-uniswap-smart-router-conf
          resources:
            limits:
              memory: "600M"
              cpu: "0.3"
            requests:
              memory: "100M"
              cpu: "0.1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9101
            timeoutSeconds: 30
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9101
            timeoutSeconds: 30
          ports:
            - containerPort: 9101

---
apiVersion: v1
kind: Service
metadata:
  name: dapdap-uniswap-smart-router-svc
  namespace: dapdap-pre
spec:
  type: ClusterIP
  selector:
    app: dapdap-uniswap-smart-router
  ports:
    - port: 9101
      protocol: TCP
      name: port9101