# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo update
# helm install redis bitnami/redis -f value.yaml -n refuel-dev

## Enable Redis Sentinel
sentinel:
  enabled: true

## Redis configuration
master:
  service:
    type: LoadBalancer
  persistence:
    storageClass: "ops-storages"
    size: 10Gi

replica:
  replicaCount: 2
  persistence:
    storageClass: "ops-storages"
    size: 10Gi

image:
  tag: "6.2.6"


