apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    ingress.vke.volcengine.com/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
spec:
  tls:
  - hosts:
    - nginx.bobdev.link
    secretName: bobdev-link-tls  # 引用上面创建的Secret
  rules:
  - host: nginx.bobdev.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
