apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# 推荐独立 namespace
namespace: cert-manager
## 开启 Helm Charts
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2   # 换成你需要的版本，对应 cert-manager release
    releaseName: cert-manager
    includeCRDs: true  # 必须启用 CRDs
    namespace: cert-manager
    valuesInline:
      installCRDs: true
      namespace: cert-manager
    valuesFile: values.yaml
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: 9.1.11
    releaseName: reflector
    namespace: cert-manager