apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  tls:
  - hosts:
    - nginx.bobdev.link
    secretName: bobdev-link-wildcard  # 引用上面创建的Secret
  rules:
  - host: nginx.bobdev.link
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
