apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bobdev-link-wildcard
  namespace: cert-manager
spec:
  secretName: bobdev-link-tls  # 最终证书存在这个 secret 里，Ingress 直接用
  issuerRef:
    name: letsencrypt-dns-route53  # 与clsuter_issuer.yaml 中 Issuer 名称一致
    kind: ClusterIssuer
  commonName: '*.bobdev.link'
  dnsNames:
    - '*.bobdev.link'
    - 'bobdev.link'  # 可选，顺便申请根域名
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "test,bob-data-dev"  # 同步到test
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "test,bob-data-dev"