apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beratown-pre
resources:
  - beratown-api/beratown-api.yaml
  - beratown-go-api/beratown-go-api.yaml
  - beratown-tool/beratown-tool.yaml
  - service-account/beratownagentserviceaccount.yaml